clean:
	-rm multiThreads singleThread
singleThread:
	gcc singleThread.c -o singleThread
multiThreads:
	gcc multiThreads.c -o multiThreads
execute_single:
	./singleThread
execute_multi:
	./multiThreads
